export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const LOAD_DICTIONARIES = 'LOAD_DICTIONARIES';
export const DICTIONARIES_READY = 'DICTIONARIES_READY';
export const ACTIVE_DICTIONARY_CHANGED = 'ACTIVE_DICTIONARY_CHANGED';

export const LOAD_STUDY = 'LOAD_STUDY';
export const STUDY_READY = 'STUDY_READY';
export const STUDY_FAILED = 'STUDY_FAILED';
export const LEAVE_STUDY = 'LEAVE_STUDY';
